models:
  gpt-4_1-mini:
    provider: openai
    model_name: gpt-4.1-mini
    max_tokens: 8192
    temperature: 0.0
    max_workers: 64
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 3
    timeout: 60

  gpt-4_1:
    provider: openai
    model_name: gpt-4.1
    max_tokens: 8192
    temperature: 0.0
    max_workers: 64
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 3
    timeout: 60

  o4-mini:
    provider: openai
    model_name: o4-mini
    max_completion_tokens: 8192
    temperature: 1.0
    max_workers: 64
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 3
    timeout: 120

  gpt-5-mini:
    provider: openai
    model_name: gpt-5-mini
    max_completion_tokens: 32768
    temperature: 1.0
    max_workers: 32
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 3
    timeout: 180

  gpt-5:
    provider: openai
    model_name: gpt-5
    max_completion_tokens: 32768
    temperature: 1.0
    max_workers: 128
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 5
    timeout: 300

  gemini-2_5-pro:
    provider: openai
    organization: google
    model_name: gemini-2.5-pro
    max_tokens: 32768
    temperature: 0
    max_workers: 64
    base_url: https://generativelanguage.googleapis.com/v1beta/openai/
    timeout: 500
    max_retries: 5

  gemini-2_5-pro-2:
    provider: openai
    organization: google-2
    model_name: gemini-2.5-pro
    max_tokens: 32768
    temperature: 0
    max_workers: 64
    base_url: https://generativelanguage.googleapis.com/v1beta/openai/
    timeout: 500
    max_retries: 5

  gemini-2_5-flash:
    provider: openai
    organization: google
    model_name: gemini-2.5-flash
    max_tokens: 8192
    temperature: 0
    max_workers: 20
    base_url: https://generativelanguage.googleapis.com/v1beta/openai/
    timeout: 180
    max_retries: 3

  claude-4-sonnet:
    provider: anthropic
    model_name: claude-sonnet-4-20250514
    max_tokens: 16384
    temperature: 0
    max_workers: 128

  gpt-oss-20b:
    provider: together
    model_name: openai/gpt-oss-20b
    max_tokens: 8192
    temperature: 0
    max_workers: 16

  gpt-oss-120b:
    provider: together
    model_name: openai/gpt-oss-120b
    max_tokens: 8192
    temperature: 0
    max_workers: 8
    timeout: 120

  qwen2_5-vl-72b:
    provider: openai
    organization: self-hosted
    model_name:  Qwen/Qwen2.5-VL-72B-Instruct
    max_tokens: 8192
    temperature: 0
    max_workers: 10
    base_url: https://api.revered.me/v1
    timeout: 180

  qwen3-235b-a22b-thinking:
    provider: together
    model_name:  Qwen/Qwen3-235B-A22B-Thinking-2507
    max_tokens: 8192
    temperature: 0
    max_workers: 16
    timeout: 300

  qwen3-235b-a22b-instruct:
    provider: together
    model_name:  Qwen/Qwen3-235B-A22B-Instruct-2507-tput
    max_tokens: 8192
    temperature: 0
    max_workers: 16
    timeout: 180

  internvl3_5:
    provider: openai
    organization: self-hosted
    model_name: internvl3.5-241b-a28b
    max_tokens: 16384
    temperature: 0
    max_workers: 64
    base_url: https://api.revered.me/v1
    timeout: 500

  glm-4_5v:
    provider: openai
    organization: self-hosted
    model_name: GLM-4.5V
    max_tokens: 16384
    temperature: 0
    max_workers: 32
    base_url: https://api.revered.me/v1
    timeout: 180

  azure-gpt-5:
    provider: azure_openai
    model_name: o3
    max_completion_tokens: 32768
    temperature: 1.0
    max_workers: 32
    max_retries: 5
    timeout: 300